name:   Reseteo de calorias

on:
  schedule:
    - cron: '1 0 * * *'  # Ejecuta todos los días a las 00:01
  workflow_dispatch: # Permite ejecutar manualmente desde la interfaz de GitHub

jobs:
  run-cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run curl command
        run: curl -X POST https://backendabmprojects.vercel.app/api/resetCalories
