name: Run cron job

on:
  schedule:
    - cron: '* * * * *'  # Ejecutar cada hora en el minuto 0
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

jobs:
  run-cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Make API Request
        run: |
          curl -X POST https://backendabmprojects.vercel.app/api/resetCalories
